import type { Flow, FlowStep } from "./ir.ts";

/**
 * flow-diff.ts — step-level 3-way diff + merge (E21, janus-specs/R4-selfheal-collab/E21-
 * collaboration.md). Pure, isomorphic — no fetch/DOM/filesystem.
 *
 * Podium flow steps carry a STABLE `id` (a UUID assigned once at authoring time, never
 * regenerated by an edit — see src/step-tree.ts's `setAtPath`, which only ever mutates a step's
 * fields, never its id) — so a step's identity across two divergently-edited copies of the same
 * flow is exactly its `id`. That's the key this diff operates on.
 *
 * Containers (`if`/`repeat`, E4) are diffed as ONE opaque unit — their own id plus a deep-equal
 * check of their entire subtree, same as any leaf step. A change to a step buried three levels
 * inside a `repeat` shows up as "the repeat step changed," not as a separate entry for the
 * nested step. This is a deliberate, disclosed scope choice: drilling into WHICH nested child
 * changed is a real usability improvement but not required by any E21 AC (which only names
 * "step-level added/removed/changed"), and keeping containers atomic keeps the merge algorithm
 * (and its ordering rules) uniform for every step shape without a second, container-aware code
 * path.
 *
 * Three-way merge, when a common `base` is available (E21 spec AC1 vs AC4):
 *   - unchanged in both mine and theirs relative to base -> unchanged, no action needed.
 *   - changed in exactly ONE of {mine, theirs} relative to base -> auto-applies that side's
 *     version, no conflict (AC1: "non-overlapping step changes... completes a merge").
 *   - changed in BOTH, to the SAME resulting content -> no conflict (they agreed).
 *   - changed in BOTH, to DIFFERENT content -> a real conflict (AC4): surfaced explicitly,
 *     blocks merge completion until the QA picks/edits a resolution.
 *   - added only in mine, or only in theirs -> auto-included, no conflict.
 *   - added independently in BOTH with the same id but different content -> conflict (an
 *     extremely unlikely UUID collision, but handled rather than silently picking one side).
 *   - removed in one side, unchanged in the other -> auto-removed, no conflict.
 *   - removed in one side, CHANGED in the other -> conflict (edit-vs-delete).
 *
 * Without a `base` (no snapshot was ever stashed for this flow — e.g. the very first time it's
 * shared), a true 3-way classification isn't possible: this module falls back to a CONSERVATIVE
 * 2-way rule — any step id present in both `mine` and `theirs` with differing content is always
 * treated as a conflict requiring explicit resolution, never guessed. This is strictly SAFER
 * than the non-negotiable "never silently auto-resolved" bar requires, not a corner cut.
 */

export type StepChangeKind = "unchanged" | "added" | "removed" | "changed";

export interface StepDiffEntry {
  id: string;
  kind: StepChangeKind;
  /** The step's content in the recipient's own current flow — absent when `kind` is "added"
   * from theirs' side only (mine never had this id). */
  mine?: FlowStep;
  /** The step's content in the incoming bundle's flow — absent when mine removed it and theirs
   * never re-added it. */
  theirs?: FlowStep;
  base?: FlowStep;
  /** True when this entry needs an explicit QA choice before the merge can complete (AC4). */
  conflict: boolean;
}

export interface FlowDiffResult {
  entries: StepDiffEntry[];
  hasConflicts: boolean;
  /** True when the diff was computed WITHOUT a common base (2-way fallback) — surfaced so the
   * UI can explain why even a clearly one-sided-looking change might still show as a conflict. */
  usedFallback: boolean;
}

function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  return JSON.stringify(a) === JSON.stringify(b);
}

function indexById(steps: FlowStep[]): Map<string, FlowStep> {
  const m = new Map<string, FlowStep>();
  for (const s of steps) m.set(s.id, s);
  return m;
}

/**
 * Diff `mine` (the recipient's current flow) against `theirs` (the incoming bundle's flow),
 * relative to `base` (the flows' last common ancestor, from `FlowBundle.baseFlow` — see
 * shared/bundle.ts) when one is available. Never mutates any input.
 */
export function diffFlows(base: Flow | undefined, mine: Flow, theirs: Flow): FlowDiffResult {
  const baseSteps = base ? indexById(base.steps) : undefined;
  const mineSteps = indexById(mine.steps);
  const theirSteps = indexById(theirs.steps);

  // Stable iteration order: base's own order first (if we have one), then any id that's new to
  // mine, then any id that's new to theirs — deterministic and never drops an id from either side.
  const order: string[] = [];
  const seen = new Set<string>();
  function push(id: string) {
    if (!seen.has(id)) {
      seen.add(id);
      order.push(id);
    }
  }
  if (base) for (const s of base.steps) push(s.id);
  for (const s of mine.steps) push(s.id);
  for (const s of theirs.steps) push(s.id);

  const usedFallback = !base;
  const entries: StepDiffEntry[] = [];

  for (const id of order) {
    const b = baseSteps?.get(id);
    const m = mineSteps.get(id);
    const t = theirSteps.get(id);

    if (m === undefined && t === undefined) continue; // gone from both — nothing to report

    if (!usedFallback) {
      // ── True 3-way classification ──────────────────────────────────────────
      // `b === undefined` first, BEFORE the removal branches below: with no base entry at all,
      // an id missing from one side means "never added there," not "removed from there" — these
      // are two very different situations and must not share a branch.
      if (b === undefined) {
        if (m === undefined || t === undefined) {
          // Added by exactly one side — nothing to compare against, nothing to conflict with.
          entries.push({ id, kind: "added", mine: m, theirs: t, base: undefined, conflict: false });
        } else {
          // Added independently on BOTH sides with the same id (e.g. a UUID collision) —
          // a conflict only if they don't happen to agree on the content.
          entries.push({ id, kind: "added", mine: m, theirs: t, base: undefined, conflict: !deepEqual(m, t) });
        }
        continue;
      }

      // From here on, base DID have this id — mChanged/tChanged are meaningful "diverged from
      // the known common ancestor" signals.
      const mChanged = !deepEqual(b, m);
      const tChanged = !deepEqual(b, t);

      if (!mChanged && !tChanged) {
        entries.push({ id, kind: "unchanged", mine: m, theirs: t, base: b, conflict: false });
        continue;
      }
      if (m === undefined) {
        // mine removed it — a conflict only if theirs went on to actually edit it further.
        entries.push({ id, kind: "removed", mine: undefined, theirs: t, base: b, conflict: tChanged });
        continue;
      }
      if (t === undefined) {
        // theirs removed it — a conflict only if mine went on to actually edit it further.
        entries.push({ id, kind: "removed", mine: m, theirs: undefined, base: b, conflict: mChanged });
        continue;
      }
      // Present in base and both sides, at least one changed (checked above) — a conflict only
      // when BOTH sides diverged from base AND landed on different content; a one-sided change
      // (or both sides independently making the identical edit) applies cleanly.
      entries.push({ id, kind: "changed", mine: m, theirs: t, base: b, conflict: mChanged && tChanged && !deepEqual(m, t) });
      continue;
    }

    // ── Conservative 2-way fallback (no base available) ──────────────────────
    if (m === undefined) {
      entries.push({ id, kind: "added", mine: undefined, theirs: t, conflict: false }); // only theirs has it
    } else if (t === undefined) {
      entries.push({ id, kind: "added", mine: m, theirs: undefined, conflict: false }); // only mine has it — keep as-is
    } else if (deepEqual(m, t)) {
      entries.push({ id, kind: "unchanged", mine: m, theirs: t, conflict: false });
    } else {
      entries.push({ id, kind: "changed", mine: m, theirs: t, conflict: true }); // can't tell who "really" changed it
    }
  }

  return { entries, hasConflicts: entries.some((e) => e.conflict), usedFallback };
}

export type ConflictResolution = "mine" | "theirs";

export interface MergeResult {
  flow: Flow;
  /** Non-empty means the merge did NOT complete — every id here still needs a resolution before
   * calling this again (AC4: "requires the QA to choose... before the merge can complete"). */
  unresolvedConflicts: string[];
}

/**
 * Build the merged flow from `mine` + a diff + the QA's chosen resolutions for every conflicting
 * entry (id -> "mine" | "theirs", or a fully custom edited FlowStep). Never silently drops a
 * conflict: any conflicting id missing from `resolutions` is reported in `unresolvedConflicts`
 * and the returned `flow` is `mine` UNCHANGED — the caller (UI) must treat a non-empty
 * `unresolvedConflicts` as "merge not complete," per AC4.
 */
export function mergeFlow(
  mine: Flow,
  diff: FlowDiffResult,
  resolutions: Record<string, ConflictResolution | FlowStep> = {},
): MergeResult {
  const unresolvedConflicts = diff.entries.filter((e) => e.conflict && !(e.id in resolutions)).map((e) => e.id);
  if (unresolvedConflicts.length > 0) return { flow: mine, unresolvedConflicts };

  const steps: FlowStep[] = [];
  for (const entry of diff.entries) {
    if (entry.id in resolutions) {
      const r = resolutions[entry.id];
      if (r === "mine") {
        if (entry.mine) steps.push(entry.mine);
      } else if (r === "theirs") {
        if (entry.theirs) steps.push(entry.theirs);
      } else {
        steps.push(r); // a fully custom edited step
      }
      continue;
    }
    switch (entry.kind) {
      case "unchanged":
        if (entry.mine) steps.push(entry.mine);
        break;
      case "added":
        // Whichever side has it wins by construction (non-conflicting adds have exactly one).
        steps.push((entry.theirs ?? entry.mine)!);
        break;
      case "removed":
        break; // one side deleted it and the other didn't touch it — stays removed
      case "changed":
        // Non-conflicting change: exactly one side actually diverged from base — take it.
        steps.push((entry.mine && !deepEqual(entry.mine, entry.base) ? entry.mine : entry.theirs) ?? entry.mine!);
        break;
    }
  }

  return { flow: { ...mine, steps }, unresolvedConflicts: [] };
}
